name: Howitzer

on:
  pull_request:
    branches: master 

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 2.6.10 
          # - 2.7.6
          # - 3.0.4
          # - 3.1.2

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install packages
        run: sudo apt-get install -y jq google-chrome-stable
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rake rubocop
      - name: Run tests
        run: bundle exec rake features:bvt features:p1 features:p2
        env:
          SEXY_SETTINGS: driver=headless_chrome,